export const CHANGE_USER_NAME_INPUT = "CHANGE_USER_NAME_INPUT";
export const ADD_USER_NAME = "ADD_USER_NAME";
export const CHANGE_PENALTY_VALUE = "CHANGE_PENALTY_VALUE";
export const CALCULATE_TOTAL = "CALCULATE_TOTAL";